/* AUTOGENERATED */
/**
  ******************************************************************************
  * @file    config.h.in
  * @author  turchenkov@gmail.com
  * @version V0.0.1
  * @date    09-Nov-2018
  * @brief   This file contains global config defs
  ******************************************************************************
  */

#ifndef CONFIG_H
#define CONFIG_H

#define DESKTOP_TEST

#endif // CONFIG_H
